pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'cd /root/.jenkins/workspace/simple-python-pyinstaller-app/jenkins-sub-dir;python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
    }
}
