pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'cd /root/.jenkins/workspace/simple-python-pyinstaller-app/jenkins-sub-dir;python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'cd /root/.jenkins/workspace/simple-python-pyinstaller-app/jenkins-sub-dir;py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    sh 'cd /root/.jenkins/workspace/simple-python-pyinstaller-app/jenkins-sub-dir && junit test-reports/results.xml'
                }
            }
        }
    }
}
